---
title: "Presentation title"
subtitle: "Presentation subtitle"
author: "Author Name"
institute: "NHS Organisation"
date: "Presentation Date"
output:
  xaringan::moon_reader:
    css: 
      - default
      - css/nhsr.css
      - css/nhsr-fonts.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      after_body: [css/insert-logo.html]
---

```{r setup, include = FALSE}
library(knitr)
library(tidyverse)
library(NHSRtheme)
# set default options
opts_chunk$set(echo = FALSE,
               fig.width = 7.252,
               fig.height = 4,
               dpi = 300)

# uncomment the following lines if you want to use the NHS-R theme colours by default
# scale_fill_continuous <- partial(scale_fill_nhs, discrete = FALSE)
# scale_fill_discrete <- partial(scale_fill_nhs, discrete = TRUE)
# scale_colour_continuous <- partial(scale_colour_nhs, discrete = FALSE)
# scale_colour_discrete <- partial(scale_colour_nhs, discrete = TRUE)
```

class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
## **`r rmarkdown::metadata$subtitle`**
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

---
class: inverse, middle, center

# An inverse slide

Often used for transitions

---

# A slide where bullets appear

--

* first point

--

* second point

--

* third point

---
class: center, middle

## About Me 

.left[My Name is Bethany Pittuck...]

.right[...and I am an Assistant Psychologist(Research) at BERRI Ltd]


`r emo::ji("link")`[Bethany Pittuck @LinkedIn](www.linkedin.com/in/bethany-pittuck)

---

## First Heading 

--

## Second Heading

---

#.left[some content on the left]

--

#.right[some content on the right]

???
You can still use incremental slides here - But not when you have a slide beginning with 'class'

---
.pull-left[

.pull-left[
## first column
]
.pull-right[
## second column
]

]

.pull-right[

.pull-left[
## third column
]
.pull-right[
## fourth column
]

]

---

